package:
  name: crawlab_toolbox
  version: "0.1.14"

source:
  git_rev: v0.1.14
  git_url: https://github.com/danielnewman09/crawlab_toolbox.git

requirements:
  host:
    - python
    - setuptools
    - numpy
    - matplotlib
    - scipy

  run:
    - python

test:
  imports:

about:
  home: https://github.com/danielnewman09/crawlab_toolbox
  license: GNU GPL v3.0
  license_file: LICENSE