package:
  name: crawlab_toolbox
  version: "0.1.2"

source:
  git_rev: v0.1.2
  git_url: https://github.com/danielnewman09/crawlab-toolbox.git

requirements:
  host:
    - python
    - setuptools
    - numpy
    - matplotlib

  run:
    - python

test:
  imports:


about:
  home: https://github.com/danielnewman09/crawlab-toolbox
  license: GNU GPL v3.0
  license_file: LICENSE